version: '3'
services:
  nginx:
    container_name: sensors-nginx
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/conf/sensors.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../:/var/www
    depends_on:
      - php

  php:
    container_name: sensors-php-fpm
    build: ./php
    restart: always
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ../.git:/root/.ssh:ro
      - ../:/var/www

  db:
    container_name: sensors-db
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: {}
